// Code generated by generator, DO NOT EDIT.
package pb

import (
	"regexp"
	"strings"
)

func (re *VacancyEntity) Vet() (*VacancyEntity, error) {
	var (
		fv         string
		fvb        []byte
		resErr     error
		res        = &VacancyEntity{}
		reBreakers = regexp.MustCompile(`<.*>`)
		reSymbols  = regexp.MustCompile("['\"<>/()\\[\\];:*{}!?=\\-+_~`$^&#№%\\\\]")
		reSpaces   = regexp.MustCompile(`\s+`)
	)
	res.Id = re.Id
	fv = re.Name
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.Name = fv
	res.Active = re.Active
	res.CreatedAt = re.CreatedAt
	res.UpdatedAt = re.UpdatedAt
	fv = re.Skills
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.Skills = fv
	res.City = re.City
	res.CityLevel = re.CityLevel
	fv = re.Brand
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.Brand = fv
	res.WebsiteUrl = re.WebsiteUrl
	res.Logo = re.Logo
	res.IndustryGroups = re.IndustryGroups
	res.CompanyId = re.CompanyId
	res.Specialization = re.Specialization
	res.Metro = re.Metro
	res.SalaryBeforeTax = re.SalaryBeforeTax
	res.SalaryCurr = re.SalaryCurr
	fv = re.JobResponsibility
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.JobResponsibility = fv
	fv = re.JobRequirement
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.JobRequirement = fv
	fv = re.WorkCondition
	fv = reBreakers.ReplaceAllString(fv, "")
	fvb = reSymbols.ReplaceAll([]byte(fv), []byte(""))
	fvb = reSpaces.ReplaceAll([]byte(fvb), []byte(" "))
	fv = strings.TrimSpace(string(fvb))
	res.WorkCondition = fv
	res.CityVisibility = re.CityVisibility
	res.VacancyLanguage = re.VacancyLanguage
	res.BusinessTrips = re.BusinessTrips
	res.SelfEmployed = re.SelfEmployed
	res.IpEmployed = re.IpEmployed
	res.PaymentPeriod = re.PaymentPeriod
	res.SalaryFrom = re.SalaryFrom
	res.SalaryTo = re.SalaryTo
	res.DefaultWorkType = re.DefaultWorkType
	res.WorkType = re.WorkType
	res.Experience = re.Experience
	res.MinCustomerLanguages = re.MinCustomerLanguages
	res.DriverLicense = re.DriverLicense
	res.DriverExp = re.DriverExp
	res.HaveCar = re.HaveCar
	res.Restrictions = re.Restrictions
	res.ListRespondButton = re.ListRespondButton
	if resErr != nil {
		return nil, resErr
	}
	return res, nil
}
